version: '3.1'
services:
    frontend:
        image: ${{ env.REGISTRY }}/best-buam-Angular
        container_name: angular-frontend
        ports:
          - "80:80"
    backend:
       image: best-buam-Quarkus
       user: root
       container_name: backend-quarkus
       environment:
          
      ports:
          - "8080:8080"

