quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.hibernate-orm.database.generation=update

quarkus.http.host=0.0.0.0

quarkus.oidc.auth-server-url=http://100.94.234.78:8081/auth/realms/bestbuam
quarkus.oidc.client-id=bestbuam-backend
quarkus.oidc.credentials.secret=jdbc:postgresql://bestbuam-postgres:5432/postgres
quarkus.oidc.authentication.scopes=profile
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=http://100.94.234.78:8081/auth/realms/bestbuam
quarkus.oidc.devservices.enabled=false

keycloak.realm=bestbuam
keycloak.host=http://100.94.234.78:8081/auth/
keycloak.admin.username=admin
keycloak.admin.password=admin

quarkus.http.cors=true
quarkus.http.cors.origins=http://100.94.234.78:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=authorization,Content-Type,accept,origin,X-Requested-With
quarkus.http.cors.exposed-headers=authorization,Content-Type,accept,origin,X-Requested-With
quarkus.http.cors.access-control-allow-credentials=true
