quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_HOST}
quarkus.hibernate-orm.database.generation=update

quarkus.oidc.auth-server-url=${KEYCLOAK_URL}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID}
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.authentication.scopes=profile
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=${KEYCLOAK_ISSUER}

keycloak.realm=${KEYCLOAK_REALM}
keycloak.host=${KEYCLOAK_HOST}
keycloak.admin.username=${ADMIN_USERNAME}
keycloak.admin.password=${ADMIN_PASSWORD}

quarkus.http.cors=true
quarkus.http.cors.origins=${HTTP_ORIGINS}
quarkus.http.cors.headers=authorization,Content-Type,accept,origin,X-Requested-With
quarkus.http.cors.exposed-headers=authorization,Content-Type,accept,origin,X-Requested-With
quarkus.http.cors.methods=GET,PUT,POST,DELETE,PATCH,OPTIONS
