quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.hibernate-orm.database.generation=update

quarkus.oidc.auth-server-url=http://keycloak:8080/realms/bestbuam
quarkus.oidc.client-id=bestbuam-backend
quarkus.oidc.credentials.secret=MRbENmRDC1neSWMLoRa7Yae3hqPnYTvm
quarkus.oidc.authentication.scopes=profile

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=authorization,Content-Type,accept,origin,X-Requested-With
quarkus.http.cors.exposed-headers=authorization,Content-Type,accept,origin,X-Requested-With
quarkus.http.cors.methods=GET,PUT,POST,DELETE,PATCH,OPTIONS